scheduler:
  # run every day at 6:00 and 18:00 UTC
  cron: "0 6,18 */1 * *"
  # number of backups to keep locally
  retention: 14
  # backup operation timeout in minutes
  timeout: 60
target:
  # mongod IP or host name
  host: "{{ if getenv "MONGO_HOST" }}{{ getenv "MONGO_HOST" }}{{ else }}172.18.7.21{{ end }}"
  # mongodb port
  port: 27017
  # mongodb database name, leave blank to backup all databases
  database: "{{ if getenv "MONGO_DATABASE" }}{{ getenv "MONGO_DATABASE" }}{{ else }}test{{ end }}"
  # leave blank if auth is not enabled
  username: "{{ if getenv "MONGO_USER" }}{{ getenv "MONGO_USER" }}{{ else }}admin{{ end }}"
  password: "{{ if getenv "MONGO_PASS" }}{{ getenv "MONGO_PASS" }}{{ else }}secret{{ end }}"
  # add custom params to mongodump (eg. Auth or SSL support), leave blank if not needed
  params: "--ssl --authenticationDatabase admin"
# S3 upload (optional)
s3:
  url: "https://play.minio.io:9000"
  bucket: "backup"
  accessKey: "Q3AM3UQ867SPQQA43P2F"
  secretKey: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
  api: "S3v4"
# GCloud upload (optional)
gcloud:
  bucket: "backup"
  keyFilePath: /path/to/service-account.json
# SFTP upload (optional)
sftp:
  host: sftp.company.com
  port: 2022
  username: user
  password: secret
  # dir must exist on the SFTP server
  dir: backup
# Email notifications (optional)
smtp:
  server: smtp.company.com
  port: 465
  username: user
  password: secret
  from: mgob@company.com
  to:
    - devops@company.com
    - alerts@company.com
# Slack notifications (optional)
slack:
  url: https://hooks.slack.com/services/xxxx/xxx/xx
  channel: devops-alerts
  username: mgob
  # 'true' to notify only on failures 
  warnOnly: false
